# Generated by Django 4.2.30 on 2026-06-18 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approval',
            options={'ordering': ['status', 'id']},
        ),
        migrations.AlterModelOptions(
            name='workflow',
            options={'ordering': ['id']},
        ),
    ]
