# Generated by Django 4.2.30 on 2026-06-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_alter_approval_options_alter_workflow_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='draft',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='approval',
            name='provider',
            field=models.CharField(default='system', max_length=40),
        ),
    ]
