# Generated by Django 4.2.30 on 2026-10-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_create_cache_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='confidence',
            field=models.PositiveSmallIntegerField(blank=True, default=82, null=True),
        ),
    ]
